service: qiilog

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  region: ap-northeast-1
  environment:
    NODE_ENV: production

custom:
  serverless-offline:
    port: 4000
  apigwBinary:
    types:
      - '*/*'

functions:
  nuxt-renderer:
    runtime: nodejs8.10
    handler: handler.render
    memorySize: 512
    timeout: 30
    package:
      exclude:
        - src/**
        - workers/**
        - .vscode/**
        - "*.json"
        - yarn.lock
      include:
        - serverless.yml
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true

  get_items:
    runtime: go1.x
    handler: workers/get_items/bin/main
    package:
      exclude:
        - ./**
      include:
        - workers/get_items/bin/**

plugins:
  - serverless-offline
  - serverless-apigw-binary